MVC/MyNoteMarketPlace/MyNoteMarketPlace/Models/NotesUnderReviewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MyNoteMarketPlace.Models
{
    public class NotesUnderReviewModel
    {
        public int NoteID { get; set; }
        public string Title { get; set; }
        public string Category { get; set; }
        public string Seller { get; set; }
        public int SellerID { get; set; }
        public DateTime DateAdded { get; set; }
        public string Status { get; set; }
    }
}

MVC/MyNoteMarketPlace/MyNoteMarketPlace/Controllers/AdminNotesController.cs
using MyNoteMarketPlace.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
namespace MyNoteMarketPlace.Controllers
{
    [OutputCache(Duration = 0)]
    [RoutePrefix("Admin")]
    public class AdminNotesController : Controller
    {
        readonly private Datebase1Entities context = new Datebase1Entities();
        [Authorize(Roles = "Super Admin,Admin")]
        [Route("Notes/UnderReviewNotes")]
        // GET: AdminNotes
        public ActionResult NotesUnderReview(int? member, int? seller, string search, string sort, int? page )
        {
            // viewbag for searching, sorting and pagination
            ViewBag.Search = search;
            ViewBag.Sort = sort;
            ViewBag.PageNumber = page;
            ViewBag.Seller = seller;
            ViewBag.Member = member;

            // get id for note status submitted for review, in review
            var submittedforreviewid = context.ReferenceData.Where(x => x.Value.ToLower() == "submitted for review").Select(x => x.ID).FirstOrDefault();
            var inreviewid = context.ReferenceData.Where(x => x.Value.ToLower() == "in review").Select(x => x.ID).FirstOrDefault();

            IEnumerable<NotesUnderReviewModel> notelist;

            // get under review notes for specific users only
            if (member != null)
            {
                ViewBag.Member = member;
                ViewBag.Seller = member;

                notelist = from notes in context.SellerNotes
                           join sellers in context.Users on notes.SellerID equals sellers.ID
                           where (notes.Status == submittedforreviewid || notes.Status == inreviewid) && sellers.ID == member
                           select new NotesUnderReviewModel
                           {
                               NoteID = notes.ID,
                               SellerID = sellers.ID,
                               Title = notes.Title,
                               Category = notes.NoteCategories.Name,
                               Seller = sellers.FirstName + " " + sellers.LastName,
                               DateAdded = notes.CreatedDate.Value,
                               Status = notes.ReferenceData.Value
                           };
            }
            // get all underreview notes
            else
            {
                notelist = from notes in context.SellerNotes
                           join sellers in context.Users on notes.SellerID equals sellers.ID
                           where notes.Status == submittedforreviewid || notes.Status == inreviewid
                           select new NotesUnderReviewModel
                           {
                               NoteID = notes.ID,
                               SellerID = sellers.ID,
                               Title = notes.Title,
                               Category = notes.NoteCategories.Name,
                               Seller = sellers.FirstName + " " + sellers.LastName,
                               DateAdded = notes.CreatedDate.Value,
                               Status = notes.ReferenceData.Value
                           };
            }

            // create viewbag of sellerlist
            ViewBag.SellerList = notelist.Select(x => new {
                Value = x.SellerID,
                Text = x.Seller
            }).Distinct().ToList();

            // filter result according to selected seller
            if (seller != null)
            {
                notelist = notelist.Where(x => x.SellerID == seller).ToList();
            }

            // if search is not empty then get result based on search
            if (!String.IsNullOrEmpty(search))
            {
                search = search.ToLower();
                notelist = notelist.Where(x => x.Title.ToLower().Contains(search) ||
                                               x.Category.ToLower().Contains(search) ||
                                               x.Seller.ToLower().Contains(search) ||
                                               x.DateAdded.ToString("dd-MM-yyyy hh:mm").Contains(search) ||
                                               x.Status.ToLower().Contains(search)
                                         ).ToList();
            }

            // sorting results
            notelist = SortTableNotesUnderReview(sort, notelist);

            var result = new List<NotesUnderReviewModel>();
            result = notelist.ToList();

            return View(result.ToList().AsQueryable().ToPagedList(page ?? 1, 5));
        }

        // sorting for notes under reviews
        private IEnumerable<NotesUnderReviewModel> SortTableNotesUnderReview(string sort, IEnumerable<NotesUnderReviewModel> table)
        {
            switch (sort)
            {
                case "Title_Asc":
                    {
                        table = table.OrderBy(x => x.Title);
                        break;
                    }
                case "Title_Desc":
                    {
                        table = table.OrderByDescending(x => x.Title);
                        break;
                    }
                case "Category_Asc":
                    {
                        table = table.OrderBy(x => x.Category);
                        break;
                    }
                case "Category_Desc":
                    {
                        table = table.OrderByDescending(x => x.Category);
                        break;
                    }
                case "Seller_Asc":
                    {
                        table = table.OrderBy(x => x.Seller);
                        break;
                    }
                case "Seller_Desc":
                    {
                        table = table.OrderByDescending(x => x.Seller);
                        break;
                    }
                case "DateAdded_Asc":
                    {
                        table = table.OrderBy(x => x.DateAdded);
                        break;
                    }
                case "DateAdded_Desc":
                    {
                        table = table.OrderByDescending(x => x.DateAdded);
                        break;
                    }
                case "Status_Asc":
                    {
                        table = table.OrderBy(x => x.Status);
                        break;
                    }
                case "Status_Desc":
                    {
                        table = table.OrderByDescending(x => x.Status);
                        break;
                    }
                default:
                    {
                        table = table.OrderByDescending(x => x.DateAdded);
                        break;
                    }
            }
            return table;
        }
           // THIS 3 METHODS WORKS FOR 3 BUTTONS APPROVE,REJECTED AND IN REVIEW. 

        [Authorize(Roles = "Super Admin,Admin")]
        [Route("Notes/UnderReviewNotes/InReview/{id}")]
        public ActionResult MakeNoteInReview(int id)
        {
            // get note by id
            var note = context.SellerNotes.Where(x => x.ID == id).FirstOrDefault();

            if (note == null)
            {
                return HttpNotFound();
            }

            // get logged in user
            var user = context.Users.Where(x => x.EmailID == User.Identity.Name).FirstOrDefault();

            // notes status id for in review
            var inreviewid = context.ReferenceData.Where(x => x.Value.ToLower() == "in review").Select(x => x.ID).FirstOrDefault();

            // update status
            note.Status = inreviewid;
            note.ModifiedDate = DateTime.Now;
            note.ModifiedBy = user.ID;

            // save note in database
            context.Entry(note).State = EntityState.Modified;
            context.SaveChanges();

            return RedirectToAction("NotesUnderReview");
        }

        [Authorize(Roles = "Super Admin,Admin")]
        [Route("Notes/UnderReviewNotes/Rejected")]
        public ActionResult MakeNoteReject(FormCollection form)
        {
            // get noteid
            int noteid = Convert.ToInt32(form["noteid"]);
            // get remark
            string remark = form["remark"];

            // get note by id
            var note = context.SellerNotes.Where(x => x.ID == noteid).FirstOrDefault();

            if (note == null)
            {
                return HttpNotFound();
            }

            // get logged in user
            var user = context.Users.Where(x => x.EmailID == User.Identity.Name).First();

            // id for note status rejected
            var rejectedid = context.ReferenceData.Where(x => x.Value.ToLower() == "rejected").Select(x => x.ID).FirstOrDefault();

            // update note status
            note.Status = rejectedid;
            note.AdminRemarks = remark;
            note.ActionedBy = user.ID;
            note.ModifiedDate = DateTime.Now;
            note.ModifiedBy = user.ID;

            // save note in database
            context.Entry(note).State = EntityState.Modified;
            context.SaveChanges();

            return RedirectToAction("NotesUnderReview");
        }

        [Authorize(Roles = "Super Admin,Admin")]
        [Route("Notes/UnderReviewNotes/Publish/{id}")]
        public ActionResult MakeNotePublish(int id)
        {
            // get note
            var note = context.SellerNotes.Where(x => x.ID == id).FirstOrDefault();

            if (note == null)
            {
                return HttpNotFound();
            }

            // get logged in user
            var user = context.Users.Where(x => x.EmailID == User.Identity.Name).FirstOrDefault();

            // id for note status published

MVC/MyNoteMarketPlace/MyNoteMarketPlace/Views/AdminNotes/DownloadedNotes.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<MyNoteMarketPlace.Models.DownloadedNotesModel>
@{
    ViewBag.Title = "Downloaded Notes";
    Layout = "~/Views/Shared/_AdminNav.cshtml";
}

@{ 
    <style>

        .pagination {
            margin-left: 40% !important;
             margin-top: 10px;
           
        }

        #dashboard-publish Input[type=search] {
            width: 322px;
            border: 1px solid #d1d1d1;
            margin-bottom: 20px;
            margin-left: -100px;
        }
          .wrapper img.searchimage.doup {
            position: absolute;
            left: -40%;
            top: 23%;
        }

        .search-bar {
            height: 50px;
        }


        select {
            background-image: url("/Img/Admin/user-profile/down-arrow.png") !important;
        }

    </style>
}

<!-- Downloaded Notes -->
<section id="dashboard-publish" class="mydownload-margin">
    <div class="container">
        <div class="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                <h3>Downloaded Notes</h3>
            </div>
        </div>

        @using (Html.BeginForm("DownloadedNotes", "AdminNotes", FormMethod.Get))
        {
            <input value="@ViewBag.NoteID" name="noteid" hidden>
            <input value="@ViewBag.Member" name="member" hidden>

            <div class="row top-table">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-6">
                    <div class="row">
                        <div class="col-4 col-xs-12">
                            <p class="seller-text text-left">Notes</p>
                           
                            @Html.DropDownList("note", new SelectList(@ViewBag.NoteList, "Value", "Text", @ViewBag.Note), "Select note", new { @class = "form-control inputselect seller-dd1", id = "downloadednotes-note" })

                        </div>


                        <div class="col-4 col-xs-12">
                            <p class="seller-text text-left">Seller</p>
                           
                            @Html.DropDownList("seller", new SelectList(@ViewBag.SellerList, "Value", "Text", @ViewBag.Seller), "Select seller", new { @class = "form-control inputselect seller-dd1", id = "downloadednotes-seller" })

                        </div>

                        <div class="col-4 col-xs-12">
                            <p class="seller-text text-left">Buyer</p>
                            
                             @Html.DropDownList("buyer", new SelectList(@ViewBag.BuyerList, "Value", "Text", @ViewBag.Buyer), "Select buyer", new { @class = "form-control inputselect seller-dd1", id = "downloadednotes-buyer" })

                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-6">
                    <div class="row justify-content-end">
                        <div class="wrapper seller-mb">
                            <img src="~/Img/Admin/Dashboard/search.jpg" class="searchimage doup">
                            <input type="search"  id="search" name="search" value="@ViewBag.Search"  class="form-control search-bar InputEmail1" placeholder="Search">
                        </div>
                        <div class="btn-merge seller-mb">
                            <button type="submit" class="btn text-uppercase text-center" id="mybtn"><b>Search</b></button>
                        </div>
                    </div>
                </div>
            </div>
        }
            <div class="row">
                <div class="col-md-12">
                    <div class="grid-table table-responsive-xl">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="col" class="align-middle text-center">SR NO.</th>
                                    <th scope="col" class="align-middle">@Html.ActionLink("NOTE TITLE", "DownloadedNotes", new { selectednote = ViewBag.SelectedNote, member = ViewBag.Member, note = ViewBag.Note, sort = ViewBag.Sort == null ? "Title_Desc" : (ViewBag.Sort == "Title_Asc" ? "Title_Desc" : "Title_Asc"), search = ViewBag.Search,  seller = ViewBag.Seller, buyer = ViewBag.Buyer })</th>
                                    <th scope="col" class="align-middle">@Html.ActionLink("CATEGORY", "DownloadedNotes", new { selectednote = ViewBag.SelectedNote, member = ViewBag.Member, note = ViewBag.Note, sort = ViewBag.Sort == null ? "Category_Desc" : (ViewBag.Sort == "Category_Asc" ? "Category_Desc" : "Category_Asc"), search = ViewBag.Search, seller = ViewBag.Seller, buyer = ViewBag.Buyer })</th>
                                    <th scope="col" class="align-middle">@Html.ActionLink("BUYER", "DownloadedNotes", new { selectednote = ViewBag.SelectedNote, member = ViewBag.Member, note = ViewBag.Note, sort = ViewBag.Sort == null ? "Buyer_Desc" : (ViewBag.Sort == "Buyer_Asc" ? "Buyer_Desc" : "Buyer_Asc"), search = ViewBag.Search, seller = ViewBag.Seller, buyer = ViewBag.Buyer })</th>
                                    <th scope="col" class="align-middle">@Html.ActionLink("SELLER", "DownloadedNotes", new { selectednote = ViewBag.SelectedNote, member = ViewBag.Member, note = ViewBag.Note, sort = ViewBag.Sort == null ? "Seller_Desc" : (ViewBag.Sort == "Seller_Asc" ? "Seller_Desc" : "Seller_Asc"), search = ViewBag.Search, seller = ViewBag.Seller, buyer = ViewBag.Buyer })</th>
                                    <th scope="col" class="align-middle">@Html.ActionLink("SELL TYPE", "DownloadedNotes", new { selectednote = ViewBag.SelectedNote, member = ViewBag.Member, note = ViewBag.Note, sort = ViewBag.Sort == null ? "SellType_Desc" : (ViewBag.Sort == "SellType_Asc" ? "SellType_Desc" : "SellType_Asc"), search = ViewBag.Search, seller = ViewBag.Seller, buyer = ViewBag.Buyer })</th>
                                    <th scope="col" class="align-middle">@Html.ActionLink("PRICE", "DownloadedNotes", new { selectednote = ViewBag.SelectedNote, member = ViewBag.Member, note = ViewBag.Note, sort = ViewBag.Sort == null ? "Price_Desc" : (ViewBag.Sort == "Price_Asc" ? "Price_Desc" : "Price_Asc"), search = ViewBag.Search, seller = ViewBag.Seller, buyer = ViewBag.Buyer })</th>
                                    <th scope="col" class="align-middle" style="white-space:pre-wrap;">@Html.ActionLink("DOWNLOADED DATE/TIME", "DownloadedNotes", new { selectednote = ViewBag.SelectedNote, member = ViewBag.Member, note = ViewBag.Note, sort = ViewBag.Sort == null ? "DownloadedDate_Asc" : (ViewBag.Sort == "DownloadedDate_Desc" ? "DownloadedDate_Asc" : "DownloadedDate_Desc"), search = ViewBag.Search, seller = ViewBag.Seller, buyer = ViewBag.Buyer })</th>
                                    <th scope="col" class="align-middle"></th>
                                    <th scope="col" class="align-middle"></th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model.Count() == 0)
                                {
                                    <tr>
                                        <td colspan="10" class="text-center align-middle">No Record Found</td>
                                    </tr>
                                }
                                else
                                {
                                    int srno = 0;
                                    if (ViewBag.PageNumber == null)
                                    {
                                        srno = 0;
                                    }
                                    else
                                    {
                                        srno = (ViewBag.PageNumber - 1) * 5;
                                    }

                                    foreach (var item in Model)
                                    {
                                <tr>
                                      @{ srno = srno + 1; }
                                    <td class="align-middle">@srno</td>
                                    <td class="align-middle getpurple"><a href="@Url.Action("NoteDetail", "Admin", new { noteid = @item.NoteID })">@item.Title</a></td>
                                    <td class="align-middle">@item.Category</td>

                                    <td class="align-middle">@item.Buyer  <a href="@Url.Action("MemberDetail", "AdminMembers", new { member = @item.BuyerID })"><i class="icon-margin"><img src="~/Img/Admin/images/eye.png"></i></a></td>
                                    <td class="align-middle"> @item.Seller <a href="@Url.Action("MemberDetail", "AdminMembers", new { member = @item.SellerID })"><i class="icon-margin"><img src="~/Img/Admin/images/eye.png"></i></a></td>
                                    <td class="align-middle">@item.SellType</td>
                                    <td class="align-middle">$@item.Price</td>
                                    <td class="align-middle">@item.DownloadedDate.ToString("dd-MM-yyyy, hh:mm")</td>


                                    <td class="align-middle">
                                        <div class="dropdown">
                                            <a type="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                <img src="~/Img/Admin/images/dots.png">
                                            </a>
                                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
                                                <a class="dropdown-item" href="@Url.Action("AdminDownloadNote", "Admin", new { noteid = @item.NoteID })" role="button">Download Notes</a>
                                                <a class="dropdown-item" href="@Url.Action("NoteDetail", "Admin", new { noteid = @item.NoteID })" role="button">View More Detail</a>


                                            </div>
                                        </div>
                                    </td>
                                    <td></td>
                                </tr>


                                    }
                                }


                            </tbody>
                        </table>
                    </div>
                </div>


            </div>
        </div>
</section>
<!-- Downloaded Notes ENds -->
<!-- Pagination -->
<nav>
    <div class="container">
        <div class="row justify-content-center">


            @Html.PagedListPager(Model, page => Url.Action("DownloadedNotes", new { page, search = @ViewBag.Search, sort = @ViewBag.Sort, seller = ViewBag.Seller, buyer = ViewBag.Buyer }), new PagedList.Mvc.PagedListRenderOptions
          {
              LiElementClasses = new[] { "page-item" },
              UlElementClasses = new[] { "pagination mypagination top-page" },
              LinkToNextPageFormat = ">",
              LinkToPreviousPageFormat = "<",
              DisplayEllipsesWhenNotShowingAllPageNumbers = false,
              DisplayLinkToFirstPage = PagedListDisplayMode.Never,
              DisplayLinkToLastPage = PagedListDisplayMode.Never
          })
        </div>
    </div>
</nav>
<!-- Pagination Ends -->