MVC/MyNoteMarketPlace/MyNoteMarketPlace/Controllers/AdminProfileController.cs
using MyNoteMarketPlace.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyNoteMarketPlace.Controllers
{
   
    public class AdminProfileController : Controller
    {
        readonly private Datebase1Entities context = new Datebase1Entities();
        // GET: AdminProfile
        [HttpGet]
        [Authorize(Roles = "Admin")]
        [Route("Admin/Profile")]
        public ActionResult MyProfile()
        {
            // get logged in user
            var user = context.Users.Where(x => x.EmailID == User.Identity.Name).FirstOrDefault();

            // get logged in user profile
            var userprofile = context.Admin.Where(x => x.AdminID == user.ID).FirstOrDefault();

            // create AdminProfileViewModel
            AdminProfileModel adminProfileViewModel = new AdminProfileModel();
            if (userprofile != null)
            {
                adminProfileViewModel.FirstName = user.FirstName;
                adminProfileViewModel.LastName = user.LastName;
                adminProfileViewModel.Email = user.EmailID;
                adminProfileViewModel.PhoneNumberCountryCode = userprofile.PhoneNumberCountryCode;
                adminProfileViewModel.PhoneNumber = userprofile.Phone_number;

                if (userprofile.SecondaryEmailID != null)
                {
                    adminProfileViewModel.SecondaryEmail = userprofile.SecondaryEmailID;
                }

                if (userprofile.Profile_Picture != null)
                {
                    adminProfileViewModel.ProfilePictureUrl = userprofile.Profile_Picture;
                }

                // get country code list
                adminProfileViewModel.CountryCodeList = context.Countries.Where(x => x.IsActive).OrderBy(x => x.CountryCode).Select(x => x.CountryCode).ToList();
            }
            else {
                adminProfileViewModel.FirstName = user.FirstName;
                adminProfileViewModel.LastName = user.LastName;
                adminProfileViewModel.Email = user.EmailID;
                adminProfileViewModel.CountryCodeList = context.Countries.Where(x => x.IsActive).OrderBy(x => x.CountryCode).Select(x => x.CountryCode).ToList();

            }
            return View(adminProfileViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Super Admin,Admin")]
        [Route("Admin/Profile")]
        public ActionResult MyProfile(AdminProfileModel obj)
        {
            // get logged in user
            var user = context.Users.Where(x => x.EmailID == User.Identity.Name).FirstOrDefault();
            if (ModelState.IsValid)
            {

                // get  logged in user profile
                var userprofile = context.Admin.Where(x => x.AdminID == user.ID).FirstOrDefault();

                if (userprofile != null)
                {
                    // check if secondary email is already exists in User or UserProfile table or not
                    // if email already exists then give error
                    bool secondaryemailalreadyexistsinusers = context.Users.Where(x => x.EmailID == obj.SecondaryEmail).Any();
                    bool secondaryemailalreadyexistsinuserprofile = context.Admin.Where(x => x.SecondaryEmailID == obj.Email && x.ID != user.ID).Any();
                    if (secondaryemailalreadyexistsinusers || secondaryemailalreadyexistsinuserprofile)
                    {
                        ModelState.AddModelError("SecondaryEmail", "This email address is already exists");
                        obj.CountryCodeList = context.Countries.Where(x => x.IsActive).OrderBy(x => x.CountryCode).Select(x => x.CountryCode).ToList();
                        return View(obj);
                    }

                    // update user's data            
                    user.FirstName = obj.FirstName.Trim();
                    user.LastName = obj.LastName.Trim();
                    // update userprofile's data
                    userprofile.SecondaryEmailID = obj.SecondaryEmail.Trim();
                    userprofile.PhoneNumberCountryCode = obj.PhoneNumberCountryCode.Trim();
                    userprofile.Phone_number = obj.PhoneNumber.Trim();

                    // user upploaded profile picture and there is also previous profile picture then delete previous profile picture
                    if (userprofile.Profile_Picture != null && obj.ProfilePicture != null)
                    {
                        string path = Server.MapPath(userprofile.Profile_Picture);
                        FileInfo file = new FileInfo(path);
                        if (file.Exists)
                        {
                            file.Delete();
                        }
                    }

                    // save new profile picture and update data in userprofile table
                    if (obj.ProfilePicture != null)
                    {
                        // get extension
                        string fileextension = System.IO.Path.GetExtension(obj.ProfilePicture.FileName);
                        // set new name of file
                        string newfilename = "DP_" + DateTime.Now.ToString("ddMMyyyy_hhmmss") + fileextension;
                        // set where to save picture
                        string profilepicturepath = "~/Members/" + userprofile.ID + "/";
                        // create directory if not exists
                        CreateDirectoryIfMissing(profilepicturepath);
                        // get physical path and save profile picture there
                        string path = Path.Combine(Server.MapPath(profilepicturepath), newfilename);
                        obj.ProfilePicture.SaveAs(path);
                        // save path in database
                        userprofile.Profile_Picture = profilepicturepath + newfilename;
                    }

                    // update userprofile's data
                    userprofile.ModifiedDate = DateTime.Now;
                    userprofile.ModifiedBy = user.ID;

                    // update data and save data in database
                    context.Entry(user).State = EntityState.Modified;
                    context.Entry(userprofile).State = EntityState.Modified;
                    context.SaveChanges();

                }
                else {
                       Admin admin_profile = new Admin();

                        admin_profile.AdminID = user.ID;


                    // check if secondary email is already exists in User or UserProfile table or not
                    // if email already exists then give error
                    bool secondaryemailalreadyexistsinusers = context.Users.Where(x => x.EmailID == obj.SecondaryEmail).Any();
                    bool secondaryemailalreadyexistsinuserprofile = context.Admin.Where(x => x.SecondaryEmailID == obj.Email && x.AdminID != user.ID).Any();
                    if (secondaryemailalreadyexistsinusers || secondaryemailalreadyexistsinuserprofile)
                    {
                        ModelState.AddModelError("SecondaryEmail", "This email address is already exists");
                        obj.CountryCodeList = context.Countries.Where(x => x.IsActive).OrderBy(x => x.CountryCode).Select(x => x.CountryCode).ToList();
                        return View(obj);
                    }

                    // update user's data            
                    user.FirstName = obj.FirstName.Trim();
                    user.LastName = obj.LastName.Trim();
                    admin_profile.FirstName = obj.FirstName.Trim();
                    admin_profile.LastName = obj.LastName.Trim();
                    admin_profile.EmailID = obj.Email.Trim();
                    // update userprofile's data
                    admin_profile.SecondaryEmailID = obj.SecondaryEmail.Trim();
                    admin_profile.PhoneNumberCountryCode = obj.PhoneNumberCountryCode.Trim();
                    admin_profile.Phone_number = obj.PhoneNumber.Trim();
                    admin_profile.CreatedDate = DateTime.Now;
                    admin_profile.CreatedBy = user.ID;

                    // user upploaded profile picture and there is also previous profile picture then delete previous profile picture
                    if (admin_profile.Profile_Picture != null && obj.ProfilePicture != null)
                    {
                        string path = Server.MapPath(admin_profile.Profile_Picture);
                        FileInfo file = new FileInfo(path);
                        if (file.Exists)
                        {
                            file.Delete();
                        }
                    }

                    // save new profile picture and update data in userprofile table
                    if (obj.ProfilePicture != null)
                    {
                        // get extension
                        string fileextension = System.IO.Path.GetExtension(obj.ProfilePicture.FileName);
                        // set new name of file
                        string newfilename = "DP_" + DateTime.Now.ToString("ddMMyyyy_hhmmss") + fileextension;
                        // set where to save picture
                        string profilepicturepath = "~/Members/" + admin_profile.ID + "/";
                        // create directory if not exists
                        CreateDirectoryIfMissing(profilepicturepath);
                        // get physical path and save profile picture there
                        string path = Path.Combine(Server.MapPath(profilepicturepath), newfilename);
                        obj.ProfilePicture.SaveAs(path);
                        // save path in database
                        admin_profile.Profile_Picture = profilepicturepath + newfilename;
                    }

MVC/MyNoteMarketPlace/MyNoteMarketPlace/Views/AdminProfile/MyProfile.cshtml
@model MyNoteMarketPlace.Models.AdminProfileModel
@{
    ViewBag.Title = "Profile";
     Layout = "~/Views/Shared/_AdminNav.cshtml";

}
@{
    <style>
        select {
            background-image: url("/Img/Admin/user-profile/down-arrow.png") !important;
        }
    </style>
}



    <!-- My Profile -->
    <!--<form class="user-details-form">-->
    @using (Html.BeginForm("MyProfile", "AdminProfile", FormMethod.Post, new { enctype = "multipart/form-data", @class = "user-details-form" }))
    {
        @Html.AntiForgeryToken()

        <!-- Pesronal Detail -->
        <section id="personal-details" class="user-profile content-box-md">
            <div>
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="heading">
                                <h3>My Profile</h3>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="row">

                                <div class="col-md-6 col-sm-6">
                                    <!-- First Name -->
                                    <div class="form-group">
                                        <label class="mylabel">First Name*</label>
                                        <!--<input type="text" class="form-control InputEmail1" placeholder="Enter your First Name">-->
                                        @Html.TextBoxFor(model => model.FirstName, new { @class = "form-control InputEmail1", id = "first-name", placeholder = "Enter Your First Name", required = "required" })
                                        @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "form-error", style = "color:red;  padding: 0px 0px 0px 35px;" })
                                    </div>

                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6 col-sm-6">
                                    <!-- Last Name -->
                                    <div class="form-group">
                                        <label class="mylabel" for="InputEmail1">Last Name*</label>
                                        <!--  <input type="text" class="form-control InputEmail1" aria-describedby="emailHelp" placeholder="Enter your Last Name">-->
                                        @Html.TextBoxFor(model => model.LastName, new { @class = "form-control InputEmail1", id = "last-name", placeholder = "Enter your Last Name", required = "required" })
                                        @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "form-error", style = "color:red;  padding: 0px 0px 0px 35px;" })

                                    </div>

                                </div>

                            </div>
                            <div class="row">

                                <div class="col-md-6 col-sm-6">
                                    <!-- Email -->
                                    <div class="form-group">
                                        <label class="mylabel" for="InputEmail1">Email*</label>
                                        <!-- <input type="email" class="form-control InputEmail1" aria-describedby="emailHelp" placeholder="Enter your Email Address">-->
                                        @Html.TextBoxFor(model => model.Email, new { @class = "form-control InputEmail1", id = "email", type = "email", placeholder = "Enter your Email Address", required = "required", @readonly = "readonly" })
                                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "form-error", style = "color:red;  padding: 0px 0px 0px 35px;" })
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6 col-sm-6">
                                    <!-- Date Of Birth -->
                                    <div class="form-group">
                                        <label class="mylabel" for="InputEmail1">Secondary Email</label>
                                        <!--  <input type="email" class="form-control InputEmail1" aria-describedby="emailHelp" placeholder="Enter your Email Address">-->
                                        @Html.TextBoxFor(model => model.SecondaryEmail, new { @class = "form-control InputEmail1", id = "secondary-email", type = "email", placeholder = "Enter your Email Address" })
                                        @Html.ValidationMessageFor(model => model.SecondaryEmail, "", new { @class = "form-error", style = "color:red;  padding: 0px 0px 0px 35px;" })
                                    </div>

                                </div>
                            </div>

                            <div class="row">

                                <div class="col-md-6 col-sm-6">

                                    <!-- Phone Number -->
                                    <div class="form-group">
                                        <label class="mylabel">Phone Number</label>
                                        <div class="container">
                                            <div class="row">
                                                <div class="col-md-5 col-sm-5 col-3 col-xl-3 col-lg-4  nopadding">
                                                    <div class="marginright">

                                                        <!--   <select class="form-control inputselect">
                                                               <option>+91</option>
                                                           </select>-->
                                                        @Html.DropDownListFor(model => model.PhoneNumberCountryCode, new SelectList(@Model.CountryCodeList), new { @class = "form-control inputselect", id = "country-code", required = "required" })
                                                        @Html.ValidationMessageFor(model => model.PhoneNumberCountryCode, "", new { @class = "form-error", style = "color:red;  padding: 0px 0px 0px 35px;" })

                                                    </div>
                                                </div>
                                                <div class="col-md-7 col-sm-7 col-9 col-xl-9 col-lg-8 nopadding">

                                                    <!-- <input type="email" class="form-control InputEmail1" placeholder="Enter your phone number">-->
                                                    @Html.TextBoxFor(model => model.PhoneNumber, new { @class = "form-control InputEmail1", id = "phone-number", placeholder = "Enter your phone number", required = "required" })
                                                    @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "form-error", style = "color:red;  padding: 0px 0px 0px 35px;" })

                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <!-- Profile Picture -->
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <div class="upload-profile-pic">
                                            <label class="mylabel" for="InputEmail1">Profile Picture</label>


                                            <!-- <input type="file" class="form-control InputEmail1" aria-describedby="emailHelp"> -->
                                            @Html.TextBoxFor(model => model.ProfilePicture, new { @class = "form-control InputEmail1", id = "profile-picture", type = "file", accept = "image/*" })
                                            @if (!string.IsNullOrEmpty(Model.ProfilePictureUrl))
                                            {
                                                <p class="mylabel">To see your previously uploaded profile picture <a href="@Url.Content(Model.ProfilePictureUrl)" target="_blank">Click Here</a></p>
                                            }
                                            <div class="uploadmypic text-center">
                                                <img class="img-fluid" src="~/Img/Admin/user-profile/upload.png">
                                                <h6>Upload a picture</h6>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-2 col-sm-3">
                                    <button type="submit" class="btn text-uppercase text-center" id="mybtn"><b>submit</b></button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </section>
        <!--- </form> -->
    }
    <!-- My Profile Ends -->
   