MVC/MyNoteMarketPlace/MyNoteMarketPlace/Controllers/AdminReportsController.cs
using MyNoteMarketPlace.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyNoteMarketPlace.Controllers
{
    [OutputCache(Duration = 0)]
    [RoutePrefix("Admin")]
    public class AdminReportsController : Controller
    {
        readonly private Datebase1Entities context = new Datebase1Entities();

        // GET: AdminReports
        [Authorize(Roles = "Super Admin,Admin")]
        [Route("SpamReport")]
        public ActionResult SpamReport(string search, string sort, int? page )
        {
            // viewbag for searching, sorting and pagination
            ViewBag.Search = search;
            ViewBag.Sort = sort;
            ViewBag.PageNumber = page;

            // get spam report data for showing in table
            IEnumerable<SpamReportModel> reportlist = from spam in context.SellerNotesReportedIssues
                                                          join note in context.SellerNotes on spam.NoteID equals note.ID
                                                          join reportedby in context.Users on spam.ReportedBYID equals reportedby.ID
                                                          select new SpamReportModel
                                                          {
                                                              ID = spam.ID,
                                                              NoteID = note.ID,
                                                              ReportedBy = reportedby.FirstName + " " + reportedby.LastName,
                                                              NoteTitle = note.Title,
                                                              Category = note.NoteCategories.Name,
                                                              Remark = spam.Remarks,
                                                              DateAdded = spam.CreatedDate.Value
                                                          };

            // get search result
            if (!String.IsNullOrEmpty(search))
            {
                search = search.ToLower();
                reportlist = reportlist.Where(x => x.ReportedBy.ToLower().Contains(search) ||
                                                   x.NoteTitle.ToLower().Contains(search) ||
                                                   x.Category.ToLower().Contains(search) ||
                                                   x.Remark.ToLower().Contains(search) ||
                                                   x.DateAdded.ToString("dd-MM-yyyy, hh:mm").Contains(search)).ToList();
            }

            // sort result
            reportlist = SortTableReportedIssue(sort, reportlist);

            var result = new List<SpamReportModel>();
            result = reportlist.ToList();

            return View(result.ToList().AsQueryable().ToPagedList(page ?? 1, 5));
        }

        // sorting for spam report
        private IEnumerable<SpamReportModel> SortTableReportedIssue(string sort, IEnumerable<SpamReportModel> table)
        {
            switch (sort)
            {
                case "ReportedBy_Asc":
                    {
                        table = table.OrderBy(x => x.ReportedBy);
                        break;
                    }
                case "ReportedBy_Desc":
                    {
                        table = table.OrderByDescending(x => x.ReportedBy);
                        break;
                    }
                case "Title_Asc":
                    {
                        table = table.OrderBy(x => x.NoteTitle);
                        break;
                    }
                case "Title_Desc":
                    {
                        table = table.OrderByDescending(x => x.NoteTitle);
                        break;
                    }
                case "Category_Asc":
                    {
                        table = table.OrderBy(x => x.Category);
                        break;
                    }
                case "Category_Desc":
                    {
                        table = table.OrderByDescending(x => x.Category);
                        break;
                    }
                case "Remark_Asc":
                    {
                        table = table.OrderBy(x => x.Remark);
                        break;
                    }
                case "Remark_Desc":
                    {
                        table = table.OrderByDescending(x => x.Remark);
                        break;
                    }
                case "DateAdded_Asc":
                    {
                        table = table.OrderBy(x => x.DateAdded);
                        break;
                    }
                case "DateAdded_Desc":
                    {
                        table = table.OrderByDescending(x => x.DateAdded);
                        break;
                    }
                default:
                    {
                        table = table.OrderByDescending(x => x.DateAdded);
                        break;
                    }
            }
            return table;
        }


        [Authorize(Roles = "Super Admin,Admin")]
        [Route("SpamReport/Delete/{id}")]
        public ActionResult DeleteSpamReport(int id)
        {
            // get spam report object by id
            var spamreport = context.SellerNotesReportedIssues.Where(x => x.ID == id).FirstOrDefault();

            // check if object is null or not
            if (spamreport == null)
            {
                return HttpNotFound();
            }

            // delete object
            context.SellerNotesReportedIssues.Remove(spamreport);
            context.SaveChanges();

            return RedirectToAction("SpamReport");
        }
    }
}

MVC/MyNoteMarketPlace/MyNoteMarketPlace/Views/AdminReports/SpamReport.cshtml
@using PagedList;
@using PagedList.Mvc;
@model  IPagedList<MyNoteMarketPlace.Models.SpamReportModel>
@{
    ViewBag.Title = "Spam Report";
    Layout = "~/Views/Shared/_AdminNav.cshtml";
}
@{
    <style>

        .pagination {
            margin-left: 40% !important;
            margin-top: 10px;
           
        }

        #dashboard-publish Input[type=search] {
            width: 322px;
            border: 1px solid #d1d1d1;
            margin-bottom: 20px;
            margin-left: -100px;
        }

        .btn-confirm .btn-no {
            margin-left: 0px !important;
        }

        .wrapper img.searchimage.doup {
            position: absolute;
            left: -40%;
            top: 23%;
        }

        .search-bar {
            height: 50px;
        }
    </style>

}

<!-- Spam Report -->
<section id="dashboard-publish" class="mydownload-margin">
    <div class="container">
        @using (Html.BeginForm("SpamReport", "AdminReports", FormMethod.Get))
        {

            <div class="row top-table">
                <div class="col-12 col-sm-12 col-md-12 col-lg-6">
                    <h3>Spam Report</h3>
                </div>
                <div class="col-12 col-sm-12 col-md-12 col-lg-6">
                    <div class="row justify-content-end">
                        <div class="wrapper">
                            <img src="~/Img/Admin/Dashboard/search.jpg" class="searchimage doup">
                            <input type="search" class="form-control search-bar InputEmail1" placeholder="Search" value="@ViewBag.Search" name="search" id="search">
                        </div>
                        <div class="btn-merge">
                            <button type="submit" class="btn text-uppercase text-center" id="mybtn"><b>Search</b></button>
                        </div>
                    </div>
                </div>
            </div>
        }
        <div class="row">
            <div class="col-md-12">
                <div class="grid-table table-responsive-xl" style="overflow-x:auto;">
                    <table class="table text-center">
                        <thead>
                            <tr>
                                <th scope="col" class="align-middle text-center">SR NO.</th>
                                <th scope="col" class="align-middle">@Html.ActionLink("REPORTED BY", "SpamReport", new { sort = ViewBag.Sort == null ? "ReportedBy_Desc" : (ViewBag.Sort == "ReportedBy_Asc" ? "ReportedBy_Desc" : "ReportedBy_Asc"), search = ViewBag.Search })</th>
                                <th scope="col" class="align-middle">@Html.ActionLink("NOTE TITLE", "SpamReport", new { sort = ViewBag.Sort == null ? "Title_Desc" : (ViewBag.Sort == "Title_Asc" ? "Title_Desc" : "Title_Asc"), search = ViewBag.Search })</th>
                                <th scope="col" class="align-middle">@Html.ActionLink("CATEGORY", "SpamReport", new { sort = ViewBag.Sort == null ? "Category_Desc" : (ViewBag.Sort == "Category_Asc" ? "Category_Desc" : "Category_Asc"), search = ViewBag.Search })</th>
                                <th scope="col" class="align-middle">@Html.ActionLink("DATE ADDED", "SpamReport", new { sort = ViewBag.Sort == null ? "DateAdded_Asc" : (ViewBag.Sort == "DateAdded_Desc" ? "DateAdded_Asc" : "DateAdded_Desc"), search = ViewBag.Search })</th>
                                <th scope="col" class="align-middle">@Html.ActionLink("REMARK", "SpamReport", new { sort = ViewBag.Sort == null ? "Remark_Desc" : (ViewBag.Sort == "Remark_Asc" ? "Remark_Desc" : "Remark_Asc"), search = ViewBag.Search})</th>
                                <th scope="col" class="align-middle">ACTION</th>
                                <th scope="col" class="align-middle"></th>
                                <th scope="col" class="align-middle"></th>
                            </tr>
                        </thead>
                        <tbody>

                            @if (Model.Count() == 0)
                            {
                                <tr>
                                    <td colspan="9" class="align-middle text-center">No Record Found</td>
                                </tr>
                            }
                            else
                            {

                                 int srno = 0;
                                    if (ViewBag.PageNumber == null)
                                    {
                                        srno = 0;
                                    }
                                    else
                                    {
                                         srno = (ViewBag.PageNumber - 1) * 5;
                                    }
                                foreach (var item in Model)
                                {
                                    <tr>
                                        @{ srno = srno + 1; }
                                        <td class="align-middle">@srno</td>
                                        <td class="align-middle">@item.ReportedBy</td>
                                        <td class="align-middle getpurple"><a href="@Url.Action("NoteDetail", "Admin", new { noteid = @item.NoteID })">@item.NoteTitle</a></td>
                                        <td class="align-middle">@item.Category</td>
                                        <td class="align-middle">@item.DateAdded.ToString("dd-MM-yyyy, hh:mm")</td>
                                        <td class="align-middle">@item.Remark</td>
                                        <td class="align-middle"><a data-toggle="modal" data-target="#confirmation-@item.ID" role="button"><img src="~/Img/Admin/images/delete.png"></a></td>

                                        <!-- Section Confirmation Box -->
                                        <div class="modal fade " id="confirmation-@item.ID" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                                            <div class="modal-dialog">
                                                <div class="modal-content">
                                                    <div class="modal-confirm-body">
                                                        <div>
                                                            <p class="confirm-text">
                                                                Are you sure you want to delete reported issue?
                                                            </p>

                                                            <div class="btn-confirm">
                                                                <a class="btn btn-yes" href="@Url.Action("DeleteSpamReport", "AdminReports", new { id = @item.ID })" role="button">YES</a>
                                                                <a class="btn btn-no" data-dismiss="modal" aria-label="Close" role="button">NO</a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <!-- Section Confirmation-Box END -->

                                        <td class="align-middle">
                                            <div class="dropdown">
                                                <a type="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                    <img src="~/Img/Admin/images/dots.png">
                                                </a>
                                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
                                                    <a class="dropdown-item" href="@Url.Action("AdminDownloadNote", "Admin", new { noteid = @item.NoteID })" role="button">Download Notes</a>
                                                    <a class="dropdown-item" href="@Url.Action("NoteDetail", "Admin", new { noteid = @item.NoteID })" role="button">View More Detail</a>

                                                </div>
                                            </div>
                                        </td>
                                        <td></td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </div>


        </div>
    </div>
</section>
<!-- Spam Report Ends -->
<!-- Pagination -->
<nav>
    <div class="container">
        <div class="row justify-content-center">

            @Html.PagedListPager(Model, page => Url.Action("SpamReport", new { page, search = @ViewBag.Search, sort = @ViewBag.Sort }), new PagedList.Mvc.PagedListRenderOptions
           {
               LiElementClasses = new[] { "page-item" },
               UlElementClasses = new[] { "pagination mypagination top-page" },
               LinkToNextPageFormat = ">",
               LinkToPreviousPageFormat = "<",
               DisplayEllipsesWhenNotShowingAllPageNumbers = false,
               DisplayLinkToFirstPage = PagedListDisplayMode.Never,
               DisplayLinkToLastPage = PagedListDisplayMode.Never
           })
        </div>
    </div>
</nav>
<!-- Pagination ends -->